name: Build Windows Exe

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --windowed --icon=12925138.ico script.py

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: WorldCapitalsPro-Windows
        path: dist/script.exe
